### ISSUE TITLE
Update website to use Bootstrap

### ISSUE THREAD

**Issue by AlanFoster** [Light---/WebsiteWalkthrough#1]
It might be nice to update the website to use [Boostrap](http://getbootstrap.com/)

There's a bunch of cool components we could use like the [nav bar](http://getbootstrap.com/components/#navbar)

**Comment by AlanFoster** [comment]
There's some cool examples of accordions [here](http://getbootstrap.com/javascript/#collapse-example-accordion)

![image](https://cloud.githubusercontent.com/assets/1271782/12398379/542ac2f4-be0b-11e5-9c07-5a39c5df7b4a.png)

Maybe we could split out each section to use accordions maybe? Not sure, I'm just the ideas person :tractor:

**Comment by Light---** [comment]
Love the idea!

Bootstrap is on my list to implement, especially on the new index page.
