### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by AlanFoster** [Light---/WebsiteWalkthrough#2]
I love the current code samples that are shown to the user. It would be really cool to also see these highlighted too, like an IDE would do.

There's a bunch of open-source syntax highlighters/code editors that might help with this -

http://alexgorbatchev.com/SyntaxHighlighter/
https://ace.c9.io/
https://highlightjs.org/

**Comment by Light---** [comment]
Most definitely!

Will do some reading up on those asap

**Comment by Light---** [comment]
Closing as added in PR #11 :roller_coaster:
