### ISSUE TITLE
index.html missing colors

### ISSUE THREAD

**Issue by AlanFoster** [Light---/WebsiteWalkthrough#5]
The front-page isn't green like the other pages for some reason
###### Expected

Green background, blue text - 

![image](https://cloud.githubusercontent.com/assets/1271782/12398268/6c371844-be0a-11e5-83b1-1ce0fb481488.png)
###### Actual

White background, black text -

![image](https://cloud.githubusercontent.com/assets/1271782/12398272/72749aa6-be0a-11e5-86fd-6c852669b31c.png)

**Comment by Light---** [comment]
I plan on having, as well as a how to, a visual representation of only having the HTML. Simply the structure. I have added a new first page which will include all functionality.

So only the 'HTML only' page will not have the CSS.

**Comment by Light---** [comment]
As above. Closing :cactus:
